class SeedCatalogItem {
  const SeedCatalogItem({
    required this.key,
    required this.cropName,
    required this.emoji,
    required this.category,
    required this.germinationMinDays,
    required this.germinationMaxDays,
    required this.transplantMinDays,
    required this.transplantMaxDays,
    required this.harvestDaysFromTransplant,
    required this.tip,
    required this.varieties,
  });

  final String key;
  final String cropName;
  final String emoji;
  final String category;
  final int germinationMinDays;
  final int germinationMaxDays;
  final int transplantMinDays;
  final int transplantMaxDays;
  final int harvestDaysFromTransplant;
  final String tip;
  final List<String> varieties;
}

class SeedCatalog {
  const SeedCatalog._();

  static const List<SeedCatalogItem> items = [
    SeedCatalogItem(
      key: 'tomato',
      cropName: 'Tomato',
      emoji: '\u{1F345}',
      category: 'Fruiting',
      germinationMinDays: 5,
      germinationMaxDays: 10,
      transplantMinDays: 42,
      transplantMaxDays: 56,
      harvestDaysFromTransplant: 65,
      tip: 'Start warm. Harden off before transplanting outside.',
      varieties: ['Money Maker', 'Beefsteak', 'Cherry', 'Roma'],
    ),
    SeedCatalogItem(
      key: 'capsicum',
      cropName: 'Capsicum',
      emoji: '\u{1FAD1}',
      category: 'Fruiting',
      germinationMinDays: 7,
      germinationMaxDays: 14,
      transplantMinDays: 56,
      transplantMaxDays: 70,
      harvestDaysFromTransplant: 75,
      tip: 'Needs steady warmth for reliable germination.',
      varieties: ['California Wonder', 'Sweet Banana', 'Bell Mix'],
    ),
    SeedCatalogItem(
      key: 'chilli',
      cropName: 'Chilli',
      emoji: '\u{1F336}',
      category: 'Fruiting',
      germinationMinDays: 7,
      germinationMaxDays: 21,
      transplantMinDays: 56,
      transplantMaxDays: 84,
      harvestDaysFromTransplant: 80,
      tip: 'Slow starter. Keep warm and avoid overwatering.',
      varieties: ['Jalapeno', 'Cayenne', 'Birdseye', 'Habanero'],
    ),
    SeedCatalogItem(
      key: 'cucumber',
      cropName: 'Cucumber',
      emoji: '\u{1F952}',
      category: 'Cucurbit',
      germinationMinDays: 3,
      germinationMaxDays: 7,
      transplantMinDays: 21,
      transplantMaxDays: 28,
      harvestDaysFromTransplant: 50,
      tip: 'Transplant young. Avoid root disturbance.',
      varieties: ['Lebanese', 'Telegraph', 'Pickling'],
    ),
    SeedCatalogItem(
      key: 'zucchini',
      cropName: 'Zucchini',
      emoji: '\u{1F952}',
      category: 'Cucurbit',
      germinationMinDays: 4,
      germinationMaxDays: 8,
      transplantMinDays: 21,
      transplantMaxDays: 28,
      harvestDaysFromTransplant: 45,
      tip: 'Fast growing. Pot up quickly if roots fill the cell.',
      varieties: ['Black Beauty', 'Costata', 'Golden'],
    ),
    SeedCatalogItem(
      key: 'pumpkin',
      cropName: 'Pumpkin',
      emoji: '\u{1F383}',
      category: 'Cucurbit',
      germinationMinDays: 5,
      germinationMaxDays: 10,
      transplantMinDays: 21,
      transplantMaxDays: 35,
      harvestDaysFromTransplant: 100,
      tip: 'Needs space and warm soil. Do not hold too long in trays.',
      varieties: ['Crown', 'Butternut', 'Jack Be Little'],
    ),
    SeedCatalogItem(
      key: 'eggplant',
      cropName: 'Eggplant',
      emoji: '\u{1F346}',
      category: 'Fruiting',
      germinationMinDays: 7,
      germinationMaxDays: 14,
      transplantMinDays: 56,
      transplantMaxDays: 70,
      harvestDaysFromTransplant: 75,
      tip: 'Treat like capsicum: warm, steady, and sheltered.',
      varieties: ['Black Beauty', 'Long Purple', 'Listada'],
    ),
    SeedCatalogItem(
      key: 'watermelon',
      cropName: 'Watermelon',
      emoji: 'ÃƒÂ°Ã…Â¸Ã‚ÂÃ¢â‚¬Â°',
      category: 'Cucurbit',
      germinationMinDays: 4,
      germinationMaxDays: 10,
      transplantMinDays: 21,
      transplantMaxDays: 35,
      harvestDaysFromTransplant: 85,
      tip: 'Needs warmth. Transplant after frost risk has passed.',
      varieties: ['Sugar Baby', 'Crimson Sweet'],
    ),
    SeedCatalogItem(
      key: 'broccoli',
      cropName: 'Broccoli',
      emoji: '\u{1F966}',
      category: 'Brassica',
      germinationMinDays: 4,
      germinationMaxDays: 8,
      transplantMinDays: 28,
      transplantMaxDays: 42,
      harvestDaysFromTransplant: 60,
      tip: 'Cool-season crop. Avoid letting seedlings become leggy.',
      varieties: ['Green Sprouting', 'Marathon', 'Romanesco'],
    ),
    SeedCatalogItem(
      key: 'lettuce',
      cropName: 'Lettuce',
      emoji: '\u{1F96C}',
      category: 'Leafy',
      germinationMinDays: 2,
      germinationMaxDays: 7,
      transplantMinDays: 21,
      transplantMaxDays: 35,
      harvestDaysFromTransplant: 35,
      tip: 'Keep evenly moist. Germination can suffer in heat.',
      varieties: ['Cos', 'Buttercrunch', 'Oak Leaf', 'Mesclun'],
    ),
    SeedCatalogItem(
      key: 'basil',
      cropName: 'Basil',
      emoji: 'ÃƒÂ°Ã…Â¸Ã…â€™Ã‚Â¿',
      category: 'Herb',
      germinationMinDays: 5,
      germinationMaxDays: 10,
      transplantMinDays: 28,
      transplantMaxDays: 42,
      harvestDaysFromTransplant: 30,
      tip: 'Likes warmth. Pinch tips after establishment.',
      varieties: ['Sweet Genovese', 'Thai', 'Purple'],
    ),
    // COMPREHENSIVE_VEG_CATALOG_START
    SeedCatalogItem(
      key: 'carrot',
      cropName: 'Carrot',
      emoji: '\u{1F955}',
      category: 'Root',
      germinationMinDays: 10,
      germinationMaxDays: 21,
      transplantMinDays: 35,
      transplantMaxDays: 70,
      harvestDaysFromTransplant: 70,
      tip: 'Best direct sown. Keep seed bed evenly moist until emergence.',
      varieties: ['Nantes', 'Chantenay', 'Imperator', 'Paris Market'],
    ),
    SeedCatalogItem(
      key: 'beetroot',
      cropName: 'Beetroot',
      emoji: '\u{1FADB}',
      category: 'Root',
      germinationMinDays: 5,
      germinationMaxDays: 14,
      transplantMinDays: 28,
      transplantMaxDays: 56,
      harvestDaysFromTransplant: 55,
      tip: 'Sow direct or transplant young. Thin seedlings for good root size.',
      varieties: ['Detroit Dark Red', 'Boltardy', 'Chioggia', 'Golden'],
    ),
    SeedCatalogItem(
      key: 'radish',
      cropName: 'Radish',
      emoji: '\u{1F331}',
      category: 'Root',
      germinationMinDays: 3,
      germinationMaxDays: 7,
      transplantMinDays: 21,
      transplantMaxDays: 35,
      harvestDaysFromTransplant: 28,
      tip: 'Fast direct-sown crop. Keep evenly moist to avoid pithy roots.',
      varieties: ['Cherry Belle', 'French Breakfast', 'Daikon', 'Watermelon'],
    ),
    SeedCatalogItem(
      key: 'turnip',
      cropName: 'Turnip',
      emoji: '\u{1F331}',
      category: 'Root',
      germinationMinDays: 4,
      germinationMaxDays: 10,
      transplantMinDays: 28,
      transplantMaxDays: 49,
      harvestDaysFromTransplant: 50,
      tip: 'Cool-season root crop. Sow direct and thin early.',
      varieties: ['Purple Top White Globe', 'Tokyo Cross', 'Hakurei'],
    ),
    SeedCatalogItem(
      key: 'parsnip',
      cropName: 'Parsnip',
      emoji: '\u{1F955}',
      category: 'Root',
      germinationMinDays: 14,
      germinationMaxDays: 28,
      transplantMinDays: 70,
      transplantMaxDays: 120,
      harvestDaysFromTransplant: 120,
      tip: 'Slow germination. Use fresh seed and keep seed bed moist.',
      varieties: ['Hollow Crown', 'Gladiator', 'Tender and True'],
    ),
    SeedCatalogItem(
      key: 'swede',
      cropName: 'Swede',
      emoji: '\u{1F331}',
      category: 'Root',
      germinationMinDays: 5,
      germinationMaxDays: 10,
      transplantMinDays: 35,
      transplantMaxDays: 56,
      harvestDaysFromTransplant: 90,
      tip: 'Cool-season brassica root. Sow direct or transplant young.',
      varieties: ['Marian', 'Best of All', 'American Purple Top'],
    ),
    SeedCatalogItem(
      key: 'rutabaga',
      cropName: 'Rutabaga',
      emoji: '\u{1F331}',
      category: 'Root',
      germinationMinDays: 5,
      germinationMaxDays: 10,
      transplantMinDays: 35,
      transplantMaxDays: 56,
      harvestDaysFromTransplant: 90,
      tip: 'Same crop group as swede. Best in cooler weather.',
      varieties: ['Laurentian', 'American Purple Top'],
    ),
    SeedCatalogItem(
      key: 'salsify',
      cropName: 'Salsify',
      emoji: '\u{1F955}',
      category: 'Root',
      germinationMinDays: 10,
      germinationMaxDays: 21,
      transplantMinDays: 70,
      transplantMaxDays: 120,
      harvestDaysFromTransplant: 120,
      tip: 'Direct sow. Avoid transplanting because roots fork easily.',
      varieties: ['Mammoth Sandwich Island'],
    ),
    SeedCatalogItem(
      key: 'scorzonera',
      cropName: 'Scorzonera',
      emoji: '\u{1F955}',
      category: 'Root',
      germinationMinDays: 10,
      germinationMaxDays: 21,
      transplantMinDays: 70,
      transplantMaxDays: 120,
      harvestDaysFromTransplant: 120,
      tip: 'Direct sow in deep loose soil.',
      varieties: ['Black Spanish'],
    ),

    SeedCatalogItem(
      key: 'spinach',
      cropName: 'Spinach',
      emoji: '\u{1F96C}',
      category: 'Leafy',
      germinationMinDays: 5,
      germinationMaxDays: 10,
      transplantMinDays: 21,
      transplantMaxDays: 35,
      harvestDaysFromTransplant: 40,
      tip: 'Prefers cool soil. Sow succession batches.',
      varieties: ['Bloomsdale', 'Matador', 'Space'],
    ),
    SeedCatalogItem(
      key: 'silverbeet',
      cropName: 'Silverbeet',
      emoji: '\u{1F96C}',
      category: 'Leafy',
      germinationMinDays: 5,
      germinationMaxDays: 14,
      transplantMinDays: 28,
      transplantMaxDays: 42,
      harvestDaysFromTransplant: 55,
      tip: 'Hardy leafy crop. Transplant well before plants become crowded.',
      varieties: ['Fordhook Giant', 'Bright Lights', 'Lucullus'],
    ),
    SeedCatalogItem(
      key: 'rocket',
      cropName: 'Rocket',
      emoji: '\u{1F96C}',
      category: 'Leafy',
      germinationMinDays: 3,
      germinationMaxDays: 7,
      transplantMinDays: 14,
      transplantMaxDays: 28,
      harvestDaysFromTransplant: 30,
      tip: 'Fast leafy crop. Sow small batches often.',
      varieties: ['Wild Rocket', 'Astro', 'Sylvetta'],
    ),
    SeedCatalogItem(
      key: 'pak_choi',
      cropName: 'Pak choi',
      emoji: '\u{1F96C}',
      category: 'Leafy',
      germinationMinDays: 4,
      germinationMaxDays: 8,
      transplantMinDays: 21,
      transplantMaxDays: 35,
      harvestDaysFromTransplant: 40,
      tip: 'Cool-season Asian green. Avoid stress to reduce bolting.',
      varieties: ['Joi Choi', 'Mei Qing Choi', 'Shanghai'],
    ),
    SeedCatalogItem(
      key: 'bok_choy',
      cropName: 'Bok choy',
      emoji: '\u{1F96C}',
      category: 'Leafy',
      germinationMinDays: 4,
      germinationMaxDays: 8,
      transplantMinDays: 21,
      transplantMaxDays: 35,
      harvestDaysFromTransplant: 40,
      tip: 'Same sowing window as pak choi.',
      varieties: ['Baby Bok Choy', 'Shanghai', 'White Stem'],
    ),
    SeedCatalogItem(
      key: 'mizuna',
      cropName: 'Mizuna',
      emoji: '\u{1F96C}',
      category: 'Leafy',
      germinationMinDays: 3,
      germinationMaxDays: 7,
      transplantMinDays: 14,
      transplantMaxDays: 28,
      harvestDaysFromTransplant: 30,
      tip: 'Fast salad brassica. Good for cut-and-come-again harvesting.',
      varieties: ['Green Mizuna', 'Red Mizuna'],
    ),
    SeedCatalogItem(
      key: 'tatsoi',
      cropName: 'Tatsoi',
      emoji: '\u{1F96C}',
      category: 'Leafy',
      germinationMinDays: 4,
      germinationMaxDays: 8,
      transplantMinDays: 21,
      transplantMaxDays: 35,
      harvestDaysFromTransplant: 40,
      tip: 'Cold-tolerant Asian green.',
      varieties: ['Tatsoi Rosette'],
    ),
    SeedCatalogItem(
      key: 'endive',
      cropName: 'Endive',
      emoji: '\u{1F96C}',
      category: 'Leafy',
      germinationMinDays: 5,
      germinationMaxDays: 10,
      transplantMinDays: 28,
      transplantMaxDays: 42,
      harvestDaysFromTransplant: 55,
      tip: 'Cool-season salad green.',
      varieties: ['Frisee', 'Escarole'],
    ),
    SeedCatalogItem(
      key: 'chicory',
      cropName: 'Chicory',
      emoji: '\u{1F96C}',
      category: 'Leafy',
      germinationMinDays: 5,
      germinationMaxDays: 10,
      transplantMinDays: 28,
      transplantMaxDays: 42,
      harvestDaysFromTransplant: 60,
      tip: 'Cool-season leaf crop. Transplant before roots bind.',
      varieties: ['Sugarloaf', 'Catalogna'],
    ),
    SeedCatalogItem(
      key: 'radicchio',
      cropName: 'Radicchio',
      emoji: '\u{1F96C}',
      category: 'Leafy',
      germinationMinDays: 5,
      germinationMaxDays: 10,
      transplantMinDays: 28,
      transplantMaxDays: 42,
      harvestDaysFromTransplant: 70,
      tip: 'Cool-season heading chicory.',
      varieties: ['Palla Rossa', 'Treviso'],
    ),
    SeedCatalogItem(
      key: 'mustard_greens',
      cropName: 'Mustard greens',
      emoji: '\u{1F96C}',
      category: 'Leafy',
      germinationMinDays: 3,
      germinationMaxDays: 7,
      transplantMinDays: 14,
      transplantMaxDays: 28,
      harvestDaysFromTransplant: 35,
      tip: 'Fast spicy leafy green.',
      varieties: ['Red Giant', 'Green Wave'],
    ),
    SeedCatalogItem(
      key: 'collards',
      cropName: 'Collards',
      emoji: '\u{1F96C}',
      category: 'Leafy',
      germinationMinDays: 4,
      germinationMaxDays: 8,
      transplantMinDays: 28,
      transplantMaxDays: 42,
      harvestDaysFromTransplant: 60,
      tip: 'Hardy brassica leaf crop.',
      varieties: ['Georgia Southern', 'Champion'],
    ),
    SeedCatalogItem(
      key: 'watercress',
      cropName: 'Watercress',
      emoji: '\u{1F96C}',
      category: 'Leafy',
      germinationMinDays: 5,
      germinationMaxDays: 10,
      transplantMinDays: 21,
      transplantMaxDays: 35,
      harvestDaysFromTransplant: 35,
      tip: 'Needs constant moisture.',
      varieties: ['Broadleaf'],
    ),
    SeedCatalogItem(
      key: 'cress',
      cropName: 'Cress',
      emoji: '\u{1F96C}',
      category: 'Leafy',
      germinationMinDays: 2,
      germinationMaxDays: 5,
      transplantMinDays: 7,
      transplantMaxDays: 14,
      harvestDaysFromTransplant: 14,
      tip: 'Very fast microgreen or baby leaf crop.',
      varieties: ['Garden Cress'],
    ),
    SeedCatalogItem(
      key: 'corn_salad',
      cropName: 'Corn salad',
      emoji: '\u{1F96C}',
      category: 'Leafy',
      germinationMinDays: 7,
      germinationMaxDays: 14,
      transplantMinDays: 21,
      transplantMaxDays: 35,
      harvestDaysFromTransplant: 45,
      tip: 'Cool-season salad green.',
      varieties: ['Vit', 'Verte de Cambrai'],
    ),

    SeedCatalogItem(
      key: 'cabbage',
      cropName: 'Cabbage',
      emoji: '\u{1F96C}',
      category: 'Brassica',
      germinationMinDays: 4,
      germinationMaxDays: 8,
      transplantMinDays: 28,
      transplantMaxDays: 42,
      harvestDaysFromTransplant: 75,
      tip: 'Cool-season brassica. Transplant sturdy seedlings.',
      varieties: ['Drumhead', 'Savoy', 'Red Acre', 'Greyhound'],
    ),
    SeedCatalogItem(
      key: 'kale',
      cropName: 'Kale',
      emoji: '\u{1F96C}',
      category: 'Brassica',
      germinationMinDays: 4,
      germinationMaxDays: 8,
      transplantMinDays: 28,
      transplantMaxDays: 42,
      harvestDaysFromTransplant: 55,
      tip: 'Hardy leafy brassica.',
      varieties: ['Curly', 'Cavolo Nero', 'Red Russian'],
    ),
    SeedCatalogItem(
      key: 'cauliflower',
      cropName: 'Cauliflower',
      emoji: '\u{1F966}',
      category: 'Brassica',
      germinationMinDays: 4,
      germinationMaxDays: 8,
      transplantMinDays: 28,
      transplantMaxDays: 42,
      harvestDaysFromTransplant: 80,
      tip: 'Needs steady growth and fertile soil.',
      varieties: ['Snowball', 'All Year Round', 'Romanesco'],
    ),
    SeedCatalogItem(
      key: 'kohlrabi',
      cropName: 'Kohlrabi',
      emoji: '\u{1F331}',
      category: 'Brassica',
      germinationMinDays: 4,
      germinationMaxDays: 8,
      transplantMinDays: 21,
      transplantMaxDays: 35,
      harvestDaysFromTransplant: 50,
      tip: 'Fast cool-season brassica.',
      varieties: ['Purple Vienna', 'White Vienna'],
    ),
    SeedCatalogItem(
      key: 'brussels_sprouts',
      cropName: 'Brussels sprouts',
      emoji: '\u{1F96C}',
      category: 'Brassica',
      germinationMinDays: 4,
      germinationMaxDays: 8,
      transplantMinDays: 35,
      transplantMaxDays: 56,
      harvestDaysFromTransplant: 100,
      tip: 'Long-season brassica. Start early.',
      varieties: ['Long Island Improved', 'Jade Cross'],
    ),
    SeedCatalogItem(
      key: 'cavolo_nero',
      cropName: 'Cavolo nero',
      emoji: '\u{1F96C}',
      category: 'Brassica',
      germinationMinDays: 4,
      germinationMaxDays: 8,
      transplantMinDays: 28,
      transplantMaxDays: 42,
      harvestDaysFromTransplant: 55,
      tip: 'Tuscan kale. Hardy and productive.',
      varieties: ['Nero di Toscana'],
    ),
    SeedCatalogItem(
      key: 'chinese_cabbage',
      cropName: 'Chinese cabbage',
      emoji: '\u{1F96C}',
      category: 'Brassica',
      germinationMinDays: 4,
      germinationMaxDays: 8,
      transplantMinDays: 21,
      transplantMaxDays: 35,
      harvestDaysFromTransplant: 55,
      tip: 'Cool-season heading Asian brassica.',
      varieties: ['Wong Bok', 'Michihili'],
    ),
    SeedCatalogItem(
      key: 'gai_lan',
      cropName: 'Gai lan',
      emoji: '\u{1F96C}',
      category: 'Brassica',
      germinationMinDays: 4,
      germinationMaxDays: 8,
      transplantMinDays: 21,
      transplantMaxDays: 35,
      harvestDaysFromTransplant: 45,
      tip: 'Chinese broccoli. Harvest young shoots.',
      varieties: ['Green Lance'],
    ),

    SeedCatalogItem(
      key: 'onion',
      cropName: 'Onion',
      emoji: '\u{1F9C5}',
      category: 'Allium',
      germinationMinDays: 7,
      germinationMaxDays: 14,
      transplantMinDays: 56,
      transplantMaxDays: 84,
      harvestDaysFromTransplant: 120,
      tip: 'Slow starter. Keep seedlings trimmed and well lit.',
      varieties: ['Pukekohe Long Keeper', 'Red Brunswick', 'White Lisbon'],
    ),
    SeedCatalogItem(
      key: 'spring_onion',
      cropName: 'Spring onion',
      emoji: '\u{1F9C5}',
      category: 'Allium',
      germinationMinDays: 7,
      germinationMaxDays: 14,
      transplantMinDays: 35,
      transplantMaxDays: 56,
      harvestDaysFromTransplant: 65,
      tip: 'Sow succession batches. Can be direct sown or transplanted.',
      varieties: ['White Lisbon', 'Evergreen'],
    ),
    SeedCatalogItem(
      key: 'leek',
      cropName: 'Leek',
      emoji: '\u{1F9C5}',
      category: 'Allium',
      germinationMinDays: 7,
      germinationMaxDays: 14,
      transplantMinDays: 70,
      transplantMaxDays: 100,
      harvestDaysFromTransplant: 120,
      tip: 'Slow seedling crop. Transplant pencil-thick seedlings.',
      varieties: ['Musselburgh', 'King Richard', 'American Flag'],
    ),
    SeedCatalogItem(
      key: 'shallot',
      cropName: 'Shallot',
      emoji: '\u{1F9C5}',
      category: 'Allium',
      germinationMinDays: 7,
      germinationMaxDays: 14,
      transplantMinDays: 56,
      transplantMaxDays: 84,
      harvestDaysFromTransplant: 110,
      tip: 'Can be grown from seed or sets.',
      varieties: ['Zebrune', 'Ambition'],
    ),
    SeedCatalogItem(
      key: 'chives',
      cropName: 'Chives',
      emoji: '\u{1F33F}',
      category: 'Allium',
      germinationMinDays: 7,
      germinationMaxDays: 21,
      transplantMinDays: 42,
      transplantMaxDays: 70,
      harvestDaysFromTransplant: 70,
      tip: 'Perennial allium herb. Germination can be slow.',
      varieties: ['Common Chives', 'Garlic Chives'],
    ),
    SeedCatalogItem(
      key: 'garlic',
      cropName: 'Garlic',
      emoji: '\u{1F9C4}',
      category: 'Allium',
      germinationMinDays: 10,
      germinationMaxDays: 21,
      transplantMinDays: 90,
      transplantMaxDays: 160,
      harvestDaysFromTransplant: 180,
      tip: 'Usually planted from cloves rather than seed.',
      varieties: ['Printanor', 'Elephant Garlic', 'Hardneck Mix'],
    ),

    SeedCatalogItem(
      key: 'beans',
      cropName: 'Beans',
      emoji: '\u{1FAD8}',
      category: 'Legume',
      germinationMinDays: 5,
      germinationMaxDays: 10,
      transplantMinDays: 14,
      transplantMaxDays: 28,
      harvestDaysFromTransplant: 55,
      tip: 'Best direct sown once soil is warm enough.',
      varieties: ['Dwarf French', 'Runner Bean', 'Climbing Bean'],
    ),
    SeedCatalogItem(
      key: 'dwarf_beans',
      cropName: 'Dwarf beans',
      emoji: '\u{1FAD8}',
      category: 'Legume',
      germinationMinDays: 5,
      germinationMaxDays: 10,
      transplantMinDays: 14,
      transplantMaxDays: 28,
      harvestDaysFromTransplant: 55,
      tip: 'Compact beans. Direct sow in warm soil.',
      varieties: ['Provider', 'Tendergreen'],
    ),
    SeedCatalogItem(
      key: 'runner_beans',
      cropName: 'Runner beans',
      emoji: '\u{1FAD8}',
      category: 'Legume',
      germinationMinDays: 5,
      germinationMaxDays: 10,
      transplantMinDays: 14,
      transplantMaxDays: 28,
      harvestDaysFromTransplant: 65,
      tip: 'Needs support. Direct sow or transplant carefully.',
      varieties: ['Scarlet Runner', 'Painted Lady'],
    ),
    SeedCatalogItem(
      key: 'peas',
      cropName: 'Peas',
      emoji: '\u{1FADB}',
      category: 'Legume',
      germinationMinDays: 5,
      germinationMaxDays: 14,
      transplantMinDays: 14,
      transplantMaxDays: 28,
      harvestDaysFromTransplant: 60,
      tip: 'Cool-season legume. Sow direct or transplant very young.',
      varieties: ['Greenfeast', 'Telephone', 'Alderman'],
    ),
    SeedCatalogItem(
      key: 'snow_peas',
      cropName: 'Snow peas',
      emoji: '\u{1FADB}',
      category: 'Legume',
      germinationMinDays: 5,
      germinationMaxDays: 14,
      transplantMinDays: 14,
      transplantMaxDays: 28,
      harvestDaysFromTransplant: 60,
      tip: 'Cool-season climbing pea.',
      varieties: ['Oregon Sugar Pod', 'Mammoth Melting'],
    ),
    SeedCatalogItem(
      key: 'sugar_snap_peas',
      cropName: 'Sugar snap peas',
      emoji: '\u{1FADB}',
      category: 'Legume',
      germinationMinDays: 5,
      germinationMaxDays: 14,
      transplantMinDays: 14,
      transplantMaxDays: 28,
      harvestDaysFromTransplant: 65,
      tip: 'Cool-season edible pod pea.',
      varieties: ['Sugar Ann', 'Cascadia'],
    ),
    SeedCatalogItem(
      key: 'broad_beans',
      cropName: 'Broad beans',
      emoji: '\u{1FAD8}',
      category: 'Legume',
      germinationMinDays: 7,
      germinationMaxDays: 14,
      transplantMinDays: 21,
      transplantMaxDays: 35,
      harvestDaysFromTransplant: 90,
      tip: 'Cool-season legume. Handles cold better than common beans.',
      varieties: ['Aquadulce', 'Coles Early'],
    ),

    SeedCatalogItem(
      key: 'melon',
      cropName: 'Melon',
      emoji: '\u{1F348}',
      category: 'Cucurbit',
      germinationMinDays: 4,
      germinationMaxDays: 10,
      transplantMinDays: 21,
      transplantMaxDays: 35,
      harvestDaysFromTransplant: 85,
      tip: 'Needs warmth. Transplant after frost risk has passed.',
      varieties: ['Rockmelon', 'Honeydew', 'Charentais'],
    ),
    SeedCatalogItem(
      key: 'squash',
      cropName: 'Squash',
      emoji: '\u{1F3C6}',
      category: 'Cucurbit',
      germinationMinDays: 4,
      germinationMaxDays: 10,
      transplantMinDays: 21,
      transplantMaxDays: 35,
      harvestDaysFromTransplant: 70,
      tip: 'Warm-season cucurbit. Avoid root disturbance.',
      varieties: ['Pattypan', 'Delicata', 'Acorn'],
    ),
    SeedCatalogItem(
      key: 'sweetcorn',
      cropName: 'Sweetcorn',
      emoji: '\u{1F33D}',
      category: 'Fruiting',
      germinationMinDays: 5,
      germinationMaxDays: 10,
      transplantMinDays: 14,
      transplantMaxDays: 28,
      harvestDaysFromTransplant: 80,
      tip: 'Sow in blocks for pollination. Transplant only when young.',
      varieties: ['Honey and Pearl', 'Golden Bantam', 'Swift'],
    ),
    SeedCatalogItem(
      key: 'okra',
      cropName: 'Okra',
      emoji: '\u{1F331}',
      category: 'Fruiting',
      germinationMinDays: 7,
      germinationMaxDays: 14,
      transplantMinDays: 28,
      transplantMaxDays: 42,
      harvestDaysFromTransplant: 60,
      tip: 'Warm-season crop. Needs heat for strong growth.',
      varieties: ['Clemson Spineless', 'Red Burgundy'],
    ),
    SeedCatalogItem(
      key: 'tomatillo',
      cropName: 'Tomatillo',
      emoji: '\u{1F345}',
      category: 'Fruiting',
      germinationMinDays: 5,
      germinationMaxDays: 10,
      transplantMinDays: 42,
      transplantMaxDays: 56,
      harvestDaysFromTransplant: 75,
      tip: 'Grow like tomato. Plant at least two for pollination.',
      varieties: ['Toma Verde', 'Purple'],
    ),

    SeedCatalogItem(
      key: 'parsley',
      cropName: 'Parsley',
      emoji: '\u{1F33F}',
      category: 'Herb',
      germinationMinDays: 14,
      germinationMaxDays: 28,
      transplantMinDays: 42,
      transplantMaxDays: 70,
      harvestDaysFromTransplant: 70,
      tip: 'Slow germination. Soak seed before sowing if desired.',
      varieties: ['Italian Flat Leaf', 'Curled'],
    ),
    SeedCatalogItem(
      key: 'coriander',
      cropName: 'Coriander',
      emoji: '\u{1F33F}',
      category: 'Herb',
      germinationMinDays: 7,
      germinationMaxDays: 14,
      transplantMinDays: 21,
      transplantMaxDays: 35,
      harvestDaysFromTransplant: 35,
      tip: 'Sow succession batches. Bolts quickly in heat.',
      varieties: ['Slow Bolt', 'Leisure'],
    ),
    SeedCatalogItem(
      key: 'dill',
      cropName: 'Dill',
      emoji: '\u{1F33F}',
      category: 'Herb',
      germinationMinDays: 7,
      germinationMaxDays: 14,
      transplantMinDays: 21,
      transplantMaxDays: 35,
      harvestDaysFromTransplant: 40,
      tip: 'Best direct sown or transplanted very young.',
      varieties: ['Bouquet', 'Mammoth'],
    ),
    SeedCatalogItem(
      key: 'thyme',
      cropName: 'Thyme',
      emoji: '\u{1F33F}',
      category: 'Herb',
      germinationMinDays: 14,
      germinationMaxDays: 28,
      transplantMinDays: 56,
      transplantMaxDays: 84,
      harvestDaysFromTransplant: 90,
      tip: 'Slow herb seedling. Do not overwater.',
      varieties: ['Common Thyme', 'Lemon Thyme'],
    ),
    SeedCatalogItem(
      key: 'oregano',
      cropName: 'Oregano',
      emoji: '\u{1F33F}',
      category: 'Herb',
      germinationMinDays: 7,
      germinationMaxDays: 21,
      transplantMinDays: 42,
      transplantMaxDays: 70,
      harvestDaysFromTransplant: 70,
      tip: 'Small seed. Surface sow lightly.',
      varieties: ['Greek Oregano', 'Italian Oregano'],
    ),
    SeedCatalogItem(
      key: 'sage',
      cropName: 'Sage',
      emoji: '\u{1F33F}',
      category: 'Herb',
      germinationMinDays: 10,
      germinationMaxDays: 21,
      transplantMinDays: 42,
      transplantMaxDays: 70,
      harvestDaysFromTransplant: 75,
      tip: 'Perennial herb. Avoid wet roots.',
      varieties: ['Common Sage', 'Purple Sage'],
    ),
    SeedCatalogItem(
      key: 'rosemary',
      cropName: 'Rosemary',
      emoji: '\u{1F33F}',
      category: 'Herb',
      germinationMinDays: 14,
      germinationMaxDays: 28,
      transplantMinDays: 70,
      transplantMaxDays: 100,
      harvestDaysFromTransplant: 120,
      tip: 'Slow from seed. Cuttings are usually easier.',
      varieties: ['Tuscan Blue', 'Prostrate'],
    ),
    SeedCatalogItem(
      key: 'mint',
      cropName: 'Mint',
      emoji: '\u{1F33F}',
      category: 'Herb',
      germinationMinDays: 10,
      germinationMaxDays: 21,
      transplantMinDays: 42,
      transplantMaxDays: 70,
      harvestDaysFromTransplant: 60,
      tip: 'Vigorous perennial. Grow in a contained area.',
      varieties: ['Spearmint', 'Peppermint'],
    ),
    SeedCatalogItem(
      key: 'chervil',
      cropName: 'Chervil',
      emoji: '\u{1F33F}',
      category: 'Herb',
      germinationMinDays: 7,
      germinationMaxDays: 14,
      transplantMinDays: 21,
      transplantMaxDays: 35,
      harvestDaysFromTransplant: 40,
      tip: 'Cool-season herb. Sow succession batches.',
      varieties: ['Common Chervil'],
    ),
    SeedCatalogItem(
      key: 'fennel',
      cropName: 'Fennel',
      emoji: '\u{1F331}',
      category: 'Herb',
      germinationMinDays: 7,
      germinationMaxDays: 14,
      transplantMinDays: 28,
      transplantMaxDays: 42,
      harvestDaysFromTransplant: 80,
      tip: 'Bulb fennel prefers steady growth and cool conditions.',
      varieties: ['Florence', 'Bronze'],
    ),

    SeedCatalogItem(
      key: 'celery',
      cropName: 'Celery',
      emoji: '\u{1F331}',
      category: 'Leafy',
      germinationMinDays: 10,
      germinationMaxDays: 21,
      transplantMinDays: 56,
      transplantMaxDays: 84,
      harvestDaysFromTransplant: 100,
      tip: 'Slow seedling crop. Needs moisture and fertile soil.',
      varieties: ['Tall Utah', 'Golden Self Blanching'],
    ),
    SeedCatalogItem(
      key: 'celeriac',
      cropName: 'Celeriac',
      emoji: '\u{1F331}',
      category: 'Root',
      germinationMinDays: 10,
      germinationMaxDays: 21,
      transplantMinDays: 56,
      transplantMaxDays: 84,
      harvestDaysFromTransplant: 120,
      tip: 'Long-season root celery. Start early.',
      varieties: ['Prinz', 'Monarch'],
    ),
    SeedCatalogItem(
      key: 'asparagus',
      cropName: 'Asparagus',
      emoji: '\u{1F331}',
      category: 'Perennial',
      germinationMinDays: 14,
      germinationMaxDays: 28,
      transplantMinDays: 120,
      transplantMaxDays: 180,
      harvestDaysFromTransplant: 730,
      tip: 'Perennial crop. Usually planted from crowns.',
      varieties: ['Mary Washington', 'Pacific Purple'],
    ),
    SeedCatalogItem(
      key: 'artichoke',
      cropName: 'Artichoke',
      emoji: '\u{1F331}',
      category: 'Perennial',
      germinationMinDays: 10,
      germinationMaxDays: 21,
      transplantMinDays: 56,
      transplantMaxDays: 84,
      harvestDaysFromTransplant: 180,
      tip: 'Large perennial crop. Needs space.',
      varieties: ['Green Globe', 'Violetto'],
    ),
    SeedCatalogItem(
      key: 'potato',
      cropName: 'Potato',
      emoji: '\u{1F954}',
      category: 'Root',
      germinationMinDays: 14,
      germinationMaxDays: 28,
      transplantMinDays: 60,
      transplantMaxDays: 100,
      harvestDaysFromTransplant: 100,
      tip: 'Usually grown from seed potatoes rather than seed.',
      varieties: ['Agria', 'Jersey Benne', 'Desiree'],
    ),
    SeedCatalogItem(
      key: 'kumara',
      cropName: 'Kumara',
      emoji: '\u{1F360}',
      category: 'Root',
      germinationMinDays: 14,
      germinationMaxDays: 28,
      transplantMinDays: 60,
      transplantMaxDays: 100,
      harvestDaysFromTransplant: 120,
      tip: 'Usually grown from slips. Needs warmth.',
      varieties: ['Owairaka Red', 'Beauregard'],
    ),
    SeedCatalogItem(
      key: 'sweet_potato',
      cropName: 'Sweet potato',
      emoji: '\u{1F360}',
      category: 'Root',
      germinationMinDays: 14,
      germinationMaxDays: 28,
      transplantMinDays: 60,
      transplantMaxDays: 100,
      harvestDaysFromTransplant: 120,
      tip: 'Same crop group as kumara. Usually grown from slips.',
      varieties: ['Beauregard', 'Covington'],
    ),
    SeedCatalogItem(
      key: 'yacon',
      cropName: 'Yacon',
      emoji: '\u{1F360}',
      category: 'Root',
      germinationMinDays: 14,
      germinationMaxDays: 28,
      transplantMinDays: 60,
      transplantMaxDays: 100,
      harvestDaysFromTransplant: 180,
      tip: 'Usually grown from crowns rather than seed.',
      varieties: ['White Yacon'],
    ),
    // COMPREHENSIVE_VEG_CATALOG_END
  ];
  // ROBUST_SEED_CATALOG_LOOKUP_START
  // ROBUST_SEED_CATALOG_LOOKUP_START
  static SeedCatalogItem byKey(String key) {
    final normalised = _normaliseKey(key);

    for (final item in items) {
      if (_normaliseKey(item.key) == normalised) return item;
      if (_normaliseKey(item.cropName) == normalised) return item;
    }

    final aliases = <String, String>{
      'carrots': 'carrot',
      'beet': 'beetroot',
      'beets': 'beetroot',
      'radishes': 'radish',
      'turnips': 'turnip',
      'parsnips': 'parsnip',
      'rutabaga': 'swede',
      'silver beet': 'silverbeet',
      'chard': 'silverbeet',
      'swiss chard': 'silverbeet',
      'arugula': 'rocket',
      'pak choi': 'pak_choi',
      'pak choy': 'pak_choi',
      'bok choi': 'bok_choy',
      'bok choy': 'bok_choy',
      'brussel sprouts': 'brussels_sprouts',
      'brussels sprouts': 'brussels_sprouts',
      'green onion': 'spring_onion',
      'scallion': 'spring_onion',
      'spring onion': 'spring_onion',
      'spring onions': 'spring_onion',
      'onions': 'onion',
      'leeks': 'leek',
      'shallots': 'shallot',
      'garlic bulb': 'garlic',
      'bean': 'beans',
      'pea': 'peas',
      'snow peas': 'snow_peas',
      'sugar snap peas': 'sugar_snap_peas',
      'snap peas': 'sugar_snap_peas',
      'broad beans': 'broad_beans',
      'capsicum': 'capsicum',
      'pepper': 'capsicum',
      'peppers': 'capsicum',
      'chili': 'chilli',
      'courgette': 'zucchini',
      'rockmelon': 'melon',
      'sweet corn': 'sweetcorn',
      'corn': 'sweetcorn',
      'cilantro': 'coriander',
      'sweet potato': 'sweet_potato',
      'kumara': 'kumara',
    };

    final aliased = aliases[normalised];

    if (aliased != null) {
      for (final item in items) {
        if (_normaliseKey(item.key) == _normaliseKey(aliased)) return item;
      }
    }

    for (final item in items) {
      final itemKey = _normaliseKey(item.key);
      final itemName = _normaliseKey(item.cropName);

      if (itemKey.contains(normalised) ||
          itemName.contains(normalised) ||
          normalised.contains(itemKey) ||
          normalised.contains(itemName)) {
        return item;
      }
    }

    return _fallbackItem(key);
  }

  static String _normaliseKey(String value) {
    var result = value
        .trim()
        .toLowerCase()
        .replaceAll('&', 'and')
        .replaceAll(RegExp('[^a-z0-9]+'), '_')
        .replaceAll(RegExp('_+'), '_');

    while (result.startsWith('_')) {
      result = result.substring(1);
    }

    while (result.endsWith('_')) {
      result = result.substring(0, result.length - 1);
    }

    return result;
  }

  static String _titleFromKey(String value) {
    final words = _normaliseKey(
      value,
    ).split('_').where((word) => word.trim().isNotEmpty).toList();

    if (words.isEmpty) return 'Vegetable';

    return words
        .map((word) => word[0].toUpperCase() + word.substring(1))
        .join(' ');
  }

  static SeedCatalogItem _fallbackItem(String key) {
    return SeedCatalogItem(
      key: _normaliseKey(key),
      cropName: _titleFromKey(key),
      emoji: '\u{1F331}',
      category: 'Vegetable',
      germinationMinDays: 5,
      germinationMaxDays: 14,
      transplantMinDays: 28,
      transplantMaxDays: 56,
      harvestDaysFromTransplant: 70,
      tip:
          'Generic vegetable entry. Add crop-specific details later if needed.',
      varieties: const [],
    );
  }

  // ROBUST_SEED_CATALOG_LOOKUP_END
}
